/***********************************************************************************************
** Program name: Project 4
** Author: Jordan Hamilton
** Date: 11/18/2018
** Description: This fantasy fighter game prompts the user to select two fighters from the
** following possible choices: Barbarian, Blue Men, Harry Potter, Medusa, and Vampire. Once
** selected, the characters are initialized with their unique attributes and a random character
** randomly attacks the other character. The fight continues, displaying results until one
** Character's strength is depleted.
***********************************************************************************************/

#include "Menu.hpp"
#include "Game.hpp"

/***********************************************************************************************
** Description: This program can be run via the project4 executable generated by make.
***********************************************************************************************/
int main() {

  Menu* mainMenu = new Menu;
  Game* tournament = new Game;

  mainMenu->addMenuItem("Play a game");
  mainMenu->addMenuItem("Exit");

  do {

    tournament->play();

  } while (mainMenu->getIntFromPrompt(1, mainMenu->getMenuChoices(), true) != 2);


  delete mainMenu;
  mainMenu = nullptr;

  delete tournament;
  tournament = nullptr;

  return 0;

}
