/***********************************************************************************************
** Program name: Project 4
** Author: Jordan Hamilton
** Date: 11/18/2018
** Description: This fantasy fighter game prompts the user to select two fighters from the
** following possible choices: Barbarian, Blue Men, Harry Potter, Medusa, and Vampire. Once
** selected, the characters are initialized with their unique attributes and a random character
** randomly attacks the other character. The fight continues, displaying results until one
** Character's strength is depleted.
***********************************************************************************************/

#include "Menu.hpp"

/***********************************************************************************************
** Description: This program can be run via the project4 executable generated by make.
***********************************************************************************************/
int main() {

  Menu mainMenu, gameMenu;

  mainMenu.addMenuItem("Play a game");
  mainMenu.addMenuItem("Exit");

  gameMenu.addMenuItem("Barbarian");
  gameMenu.addMenuItem("Blue Men");
  gameMenu.addMenuItem("Harry Potter");
  gameMenu.addMenuItem("Medusa");
  gameMenu.addMenuItem("Vampire");

  /*
  do {
    int character1 = gameMenu.getIntChoiceFromPrompt("Who should fighter 1 be?", 1, gameMenu.getMenuChoices(), true);
    int character2 = gameMenu.getIntChoiceFromPrompt("Who should fighter 2 be?", 1, gameMenu.getMenuChoices(), true);
    Game newGame(character1, character2);

  } while (mainMenu.getIntChoiceFromPrompt(1, mainMenu.getMenuChoices(), true) != 2);
  */

  return 0;

}
