/************************************************************************************************
** Program name: Project 4
** Author: Jordan Hamilton
** Date: 11/21/2018
** Description: This fantasy fighter game prompts the user to select a number of fighters to fill
** two team lineups from the following possible fighter choices: Barbarian, Blue Men, Harry
** Potter, Medusa, and Vampire. Once selected, the characters are initialized with their unique
** attributes and the fighters at the beginning of each team lineup attack and defend,
** beginning with a random fighter attacking the other fighter. The fight continues until one
** fighter's strength is depleted, then the losing fighter is added to the top of a loser
** stack. The winning fighter is moved to the back of the team's lineup to fight later, and
** the winning team's score is incremented. Once there is a lineup with no remaining fighters,
** the score is tallied and the winning team lineup is displayed to the user, with the option
** to view the losing fighters.
************************************************************************************************/

#include "Menu.hpp"
#include "Game.hpp"

/***********************************************************************************************
** Description: This program can be run via the project4 executable generated by make.
***********************************************************************************************/
int main() {

  unsigned seed = time(0);
  srand(seed);

  Menu* mainMenu = new Menu;
  Game* tournament = new Game;

  mainMenu->addMenuItem("Play a game");
  mainMenu->addMenuItem("Exit");

  do {

    tournament->play();

  } while (mainMenu->getIntFromPrompt(1, mainMenu->getMenuChoices(), true) != 2);


  delete mainMenu;
  mainMenu = nullptr;

  delete tournament;
  tournament = nullptr;

  return 0;

}
